FROM golang:1.25-alpine

WORKDIR /app

RUN apk add --no-cache git gcc musl-dev make

# Install air for hot reloading
RUN go install github.com/air-verse/air@latest
# Install goose for migrations
RUN go install github.com/pressly/goose/v3/cmd/goose@latest

COPY go.mod go.sum ./
RUN go mod download

COPY . .

# Default command is air for the app service
CMD ["air", "-c", ".air.toml"]
