# --- Stage 1: Builder ---
FROM golang:1.25-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -o /out/api ./cmd/api

# --- Stage 2: API Runtime ---
FROM alpine:latest AS api

RUN apk add --no-cache ca-certificates tzdata

COPY --from=builder /out/api /api

EXPOSE 8080
CMD ["/api"]